<a href="https://colab.research.google.com/github/SrikanthGuggila/INeuron/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Write a function so that the columns of the output matrix are powers of the input
vector.

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
def func(x,N,increasing = False):
    if increasing == False:
        result = np.column_stack([x**(N-i-1) for i in range(N)])
    else:
        result = np.column_stack([x**i for i in range(N)])
    return result

In [ ]:
x = np.array([1, 2, 3, 5])
N =3
func(x,N,increasing=True)

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  5, 25]])

In [ ]:
func(x,N)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.


In [ ]:
from statistics import mean

In [ ]:
def movingavg(seq,k):
    if type(seq) == np.ndarray:
        seq = seq.tolist()
    l = []
    m = []
    for j in range(len(seq)-k+1):
        for i in range(len(seq)):
            l = l + [seq[i]]
            if i == k-1:
                m = m + [mean(l)]
            i = 0
        l = []
        seq.pop(i)
    m = [round(i,2) for i in m]
    return m

In [ ]:
input = np.array([10,20,30,40,50,60,70,80,90,100])
input

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
movingavg(input,4)

[25, 35, 45, 55, 65, 75, 85]

In [ ]:
input2 = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
input2

array([  3,   5,   7,   2,   8,  10,  11,  65,  72,  81,  99, 100, 150])

In [ ]:
movingavg(input2,3)

[5, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84, 93.33, 116.33]